const projects={sense:{number:'01',category:'PRODUCT DESIGN / 感官体验与拼搭玩具',title:'SENSE LAND 感知之境',description:'以自然与四季为线索，探索面向 ASD 儿童的感官拼搭玩具设计。通过磁吸连接、堆叠与旋转，让孩子以自己的节奏探索、组合，建立与世界的连接。',pages:[4,5,6,7,8,9]},glasses:{number:'02',category:'SERVICE & INTERACTION / 无障碍出行',title:'共享 · 眼镜',description:'面向听障人士的城市共享智能眼镜概念。将声音信息转为视觉与触觉提示，串联设备、租赁终端与手机界面，探索更自主的城市出行体验。',pages:[11,12,13,16,17,18,19,20]},aeroneck:{number:'03',category:'WEARABLE DESIGN / 健康产品概念',title:'AERONECK',description:'面向睡眠呼吸暂停综合征的可穿戴干预设备概念，探索呼吸监测、颈部支撑与日间训练的整合方式。以下展示产品造型与佩戴场景。',pages:[21,22,23]},mood:{number:'04',category:'PACKAGING & VISUAL / 情绪与包装',title:'MOOD CAT',description:'以炸毛、放松、治愈与开心四种猫咪情绪构建果酒包装系列。让角色表情、瓶身造型与色彩相互呼应，将日常情绪转化为可触摸的视觉语言。',pages:[24,25,26,27,28,29]}};
const dialog=document.querySelector('#project-dialog');let current=null,opener=null;
function showProject(key){const p=projects[key];if(!p)return;current=key;document.querySelector('#detail-number').textContent=p.number;document.querySelector('#detail-category').textContent=p.category;document.querySelector('#detail-title').textContent=p.title;document.querySelector('#detail-description').textContent=p.description;document.querySelector('#detail-pages').replaceChildren(...p.pages.map((n,i)=>{const image=new Image();image.src=`assets/page-${n}.webp`;image.alt=`${p.title} — 作品集第 ${n} 页`;image.loading=i===0?'eager':'lazy';return image}));if(!dialog.open){opener=document.activeElement;dialog.showModal();document.body.style.overflow='hidden'}dialog.scrollTop=0;document.querySelector('#close-dialog').focus();document.querySelector('#next-project').textContent=`下一个项目 · ${projects[Object.keys(projects)[(Object.keys(projects).indexOf(key)+1)%4]].title} ↗`}
function closeProject(){if(dialog.open)dialog.close();document.body.style.overflow='';if(location.hash.startsWith('#project='))history.replaceState(null,'',location.pathname+location.search+'#work');opener?.focus()}
document.querySelectorAll('[data-project]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();history.pushState(null,'',`#project=${a.dataset.project}`);showProject(a.dataset.project)}));document.querySelector('#close-dialog').onclick=closeProject;document.querySelector('#back-projects').onclick=closeProject;dialog.addEventListener('cancel',e=>{e.preventDefault();closeProject()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeProject()}});document.querySelector('#next-project').onclick=()=>{const keys=Object.keys(projects);const key=keys[(keys.indexOf(current)+1)%keys.length];history.replaceState(null,'',`#project=${key}`);showProject(key)};function syncHash(){const key=location.hash.replace('#project=','');if(projects[key])showProject(key);else if(dialog.open)closeProject()}window.addEventListener('popstate',syncHash);syncHash();
const motionPreference=matchMedia('(prefers-reduced-motion: reduce)');
const motionToggle=document.querySelector('.motion-toggle');
let paused=motionPreference.matches, greeting=0;
const greetings=['灵感来了，一起出发！','送你一朵好心情。','认真玩，也是一种创造。','今天，也要有点好奇心。'];
const activeDances=new Set();
function updateMotion(){document.body.classList.toggle('motion-paused',paused);motionToggle.setAttribute('aria-pressed',String(paused));motionToggle.textContent=paused?'播放动画 ▷':'暂停动画 Ⅱ';if(paused)activeDances.forEach(a=>a.cancel());}
updateMotion();motionToggle.addEventListener('click',()=>{paused=!paused;updateMotion()});
motionPreference.addEventListener('change',()=>{paused=motionPreference.matches;updateMotion()});
document.querySelectorAll('.ip-play').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.joko-speech').textContent=greetings[greeting++%greetings.length];document.querySelector('.hello').textContent=greeting%2?'Hello, friend!':"Hi, I'm Yuxi!";if(paused||motionPreference.matches)return;button.getAnimations().forEach(a=>a.cancel());const dance=button.animate([{transform:'translateY(0) rotate(0)'},{transform:'translateY(-23px) rotate(-8deg)',offset:.25},{transform:'translateY(0) rotate(6deg)',offset:.5},{transform:'translateY(-12px) rotate(-4deg)',offset:.75},{transform:'translateY(0) rotate(0)'}],{duration:850,easing:'ease-in-out'});activeDances.add(dance);dance.finished.catch(()=>{}).finally(()=>activeDances.delete(dance));}));
const motionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle('motion-offscreen',!entry.isIntersecting)),{threshold:0});
document.querySelectorAll('.hero-art,.joko-stage,.ip-strip').forEach(el=>motionObserver.observe(el));
